# Generated by Django 4.0.4 on 2022-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='clave',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
