# Generated by Django 4.0.4 on 2022-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0002_alter_colonia_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='clave',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='clave',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
